### ISSUE TITLE
Output Page Sizes

### ISSUE THREAD

**Issue by KeksTheAllmighty** [oxplot/pdftilecut#11]
Hey, first of all thank you for the amazing software!
Now, once I used it I noticed that the pages of the output PDF are actually not A4 size but are actually smaller.
This leads to my printer printing some extra white borders.

Is there a possibility to enforce A4 format on the output pages?

**Comment by oxplot** [comment]
This is expected. The size you specify is the size of each page as it's printed, not the size of the content inside the page. The margin provides space for things like page number, tile number, document title and most importantly, trim marks so the actual content can be precisely trimmed.

This has been a point of confusion for others as well, so I may address it in the implementation somehow.
