### ISSUE TITLE
Wrong dimensions for A4

### ISSUE THREAD

**Issue by porjo** [oxplot/pdftilecut#13]
I converted this PDF to A4 tiles: [github_sample.pdf](https://github.com/oxplot/pdftilecut/files/6513182/github_sample.pdf)

```
./pdftilecut -tile-size A4 -in github_sample.pdf -out github_sample_A4-2.pdf
```
output PDF: [github_sample_A4-2.pdf](https://github.com/oxplot/pdftilecut/files/6513194/github_sample_A4-2.pdf)

But the output seems to be not A4. Loading that PDF into Gimp produces images that are 737x885 pixels (I would expect 595x842)

**Comment by oxplot** [comment]
Your input's height is 6.86 inches. The output has 1 inch margin, so the height ends up being 8.86 inches. That's smaller than 11.6 inches of an A4, so that one's fine.

The width is not A4 because the size you specify isn't the output size, it's the "maximum output" size. And it's the size, including the margins.

The tiles are sized such that they all have the same size and they're all under the page size specified. Both of which are true in the output.

**Comment by porjo** [comment]
What I had in mind is output like this (plus margins):

![Screenshot from 2021-05-21 08-09-53](https://user-images.githubusercontent.com/1296987/119055831-09ff4e80-ba0d-11eb-92d1-702c8071c8e7.png)

Instead I got this:
![Screenshot from 2021-05-21 08-09-53_2](https://user-images.githubusercontent.com/1296987/119057130-403dcd80-ba0f-11eb-8d9e-c5e962898cef.png)

**Comment by oxplot** [comment]
Yep, as I explained in the other issue, to avoid having a final tile that's potentially 2mm wide (in your case) and unusable, the tile sizes are maximum, and not exact. pdftilecut then ensures that all tiles are the same size and under the maximum size specified.

**Comment by porjo** [comment]
What about the seemingly arbitrary page overlaps - that seems like a bug?

I'd prefer to have the final page 2mm wide and simply discard it. Could that behaviour be added as an option?

**Comment by oxplot** [comment]
> What about the seemingly arbitrary page overlaps - that seems like a bug?

If after trimming the output pages and stitching them together, you don't get the original content, then that's a bug. Otherwise, the amount of overlap is not something that's guaranteed or otherwise important at all.

> I'd prefer to have the final page 2mm wide and simply discard it. Could that behaviour be added as an option?

I have no use for this, but PRs are definitely welcome.
