### ISSUE TITLE
I'm not sure what pdftilecut can or can't do...

### ISSUE THREAD

**Issue by MarjaE2** [oxplot/pdftilecut#15]
I see that you can use pdftileccut to take a pdf coded for a certain page size, and split it into multiple pages coded for another size.

I don't see if I could take pdftilecut and use it to split a pdf of whatever input size, and split each input page into 4 pages 2-by-2, 6 pages 3-by-2, 6 pages 2-by-3, 9 pages 3-by-3, etc...

If it can do that, I think the readme should cover how.

If it can't, I think the readme should clarify that.

**Comment by oxplot** [comment]
Thanks for the report.

This is not a common use case and it's something that will be obvious quickly once your run the program with `-h`. There are many other features that pdftilecut does *not* have and it's unreasonable for a readme to list things a program cannot do.
