### ISSUE TITLE
Preserve scale

### ISSUE THREAD

**Issue by floretan** [oxplot/pdftilecut#20]
Thanks a lot for this nice little tool! 

I have a large PDF that I would like to print onto individual A4 pages. The original is exactly 50x50cm, but when I put the tiles together (making sure to print at 100% scale) the resulting width is slightly over 58cm. It seems that the splitting is done in a way to maximise the size for the given pages, but it would be nice to have an option to preserve the scale.

**Comment by oxplot** [comment]
Please provide sample input+output PDFs.

**Comment by floretan** [comment]
My apologies, as I generated a sample document to reproduce the issue I realized that the option to print at 100% scale must have been reset between documents, but that wasn't noticeable due to the relatively small difference. I now have documents which are perfectly at scale.
