### ISSUE TITLE
Remove generated "headers" completly

### ISSUE THREAD

**Issue by aprjanka** [oxplot/pdftilecut#22]
The tool nicely split my A3 scan to A4 pages. However the tool always put some markers in each corner (page number, lines, tool logo etc.). 
This means that I cannot print the resulting document, because it includes these markers. How can we remove these markers?

**Comment by oxplot** [comment]
This tool is specifically built to tile a page such that each tile can be printed, trimmed along the trim lines and put together to create a larger overall print.

So your use case is unfortunately not supported.

**Comment by aprjanka** [comment]
Understand. I'm using this tool on mac, for printing I'm using the preview app (no acrobat installed). In the mean time I found that when printing using 100% scaling, the crop/printer/trim lines (I don't know what is the exact term here) won't be printed. Using the preview app I can remove the lines if I select "save as pdf" in the preview print dialog (100% scaling is important).

Thank you for this great tool, now it works perfect for me!
