### ISSUE TITLE
How can I set the output size to 100% instead of the default "Small increase in output size."

### ISSUE THREAD

**Issue by rafo** [oxplot/pdftilecut#6]
I just want to output the original size of my A3 drawing tiled over several A4 pages. Is this possible? I didnt find your SmallIncreaseInOutputSize variable ;D

**Comment by oxplot** [comment]
> I just want to output the original size of my A3 drawing tiled over several A4 pages. Is this possible? I didnt find your SmallIncreaseInOutputSize variable ;D

The output canvas is always at 100% of the original size. The "small increase in output size" refers to the file size. I'll clarify this.

**Comment by rafo** [comment]
I just tested a A3 pdf and the output is much larger

**Comment by rafo** [comment]
The A3 PDF is printed over 6 A4 Pages (which is fine). I can send you the PDF if you want. Or a picture with measurements.

**Comment by oxplot** [comment]
> I can send you the PDF if you want.

Yes please send both the original and the tiled one.

**Comment by rafo** [comment]
Here they are:
[Anna_v4_tile.pdf](https://github.com/oxplot/pdftilecut/files/4896608/Anna_v4_tile.pdf)
[Anna_v4.pdf](https://github.com/oxplot/pdftilecut/files/4896609/Anna_v4.pdf)

**Comment by oxplot** [comment]
The output is what I expect.

Perhaps the point of confusion is that the tiles are not in fact A4 sized. This is because the output size you set is the maximum size, and not the exact size. pdftilecut tries to make all tiles the same size, while ensuring each tile is under the output size you specify, but as large as possible.

Does this clarify why the output is the way it is?

**Comment by oxplot** [comment]
Also note that each tile has a margin which in addition to the content, must fit inside the output size you specify.

**Comment by rafo** [comment]
So to be clear: I simply run "-tile-size A4" Then I cut at the cuting marks and glued the pages together. The result is not 390mm but more than 400mm. See picture:
![IMG_0536](https://user-images.githubusercontent.com/41793/87040211-ab642400-c1f0-11ea-93f8-aae112b23855.jpg)

I was thinking that original "content" in the PDF container is splited over n A4 files, with the same size, but with proper printer margins and cut-marks.

**Comment by oxplot** [comment]
OK, I can't print this right now, but looking at the page sizes as reported by my PDF viewer, this is what I see:

- Page size of the original PDF: `A3, Landscape (16.54 × 11.69 inch)`
- Page size of each tile is: `7.51 × 7.85 inch`

Each tile has exactly a 1 inch border. There are 3 tiles across and 2 tiles down. So let's do the math:

- Total content width of tiles across = (7.51 - 2) * 3 = 16.53
- Total content height of tiles down = (7.85 - 2) * 2 = 11.7

So they're off by 0.01 inch and that's just rounding error. The only thing I can think of is that your print settings are exactly right and the pages are being stretched before printing.

**Comment by rafo** [comment]
- Print settings: I think they are ok. I tested several pdfs. And rechecked the settings everytime.
- I will try to recreate the pdf (Its an simple Export from Autodesk Fusion 360 but I dont know if something happend with that pdf inbetween)

**Comment by rafo** [comment]
One more thing: the cutting marks are exactly at 2x2.54cm? And you can roughly see that the glued part in the picture is about 3cm? So the print settings seem to be at scale: 100%. I think the print settings are ok and I will have a look in to the "streched before printing" thing.

**Comment by oxplot** [comment]
> the cutting marks are exactly at 2x2.54cm?

[Yep.](https://github.com/oxplot/pdftilecut/blob/master/main.go#L28) Trim margin is 5/6" of an inch and bleed margin is 1/6", total of 1 inch margin around the page.
